apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kzoe-1b04"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kzoe-1b04"
  template:
    metadata:
      labels:
        app: "kzoe-1b04"
    spec:
      containers:
        - name: "kzoe-1b04"
          image: "zoereg.azurecr.io/kzoe"
          ports:
          - containerPort: 80