apiVersion: v1
kind: Service
metadata:
    name: "kzoe-1b04"
    labels:
        app: "kzoe-1b04"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kzoe-1b04"